### PR TITLE
Clean up OLX

### PR DESCRIPTION
**Pull request by bradenmacdonald**
MNG-369

Studio exports OLX that consists of as many tiny files as possible (why?!). This is hard to edit by hand, and doesn't show nice diffs on GitHub.

Here I have consolidated the OLX so that there is one file per sequential (subsection). This will produce _much_ nicer diffs in the future and be way easier to edit by hand, especially when moving things around. However, it does mean that editing in Studio and then exporting the course would not be supported as that would undo this work. Personally, I find the hand-editing workflow easier when the changes must be reviewed on GitHub (e.g. you never need an "Export" step; you simply push the changes to GitHub and use its auto-generated tarball link).

For now I've only tried this out with the "First Sprint" subsection.

Tarball link: https://github.com/open-craft/courses/archive/onboarding-cleanup.tar.gz

Preview link: https://courses.opencraft.com/courses/course-v1:OpenCraft+onboarding-dev+course/courseware/chapter_newcomer/first_sprint/?child=first (I have already imported the new tarball, but there's not much to see - there should be no visible changes).

This won't change any URLs.

To keep this review simple, I have not changed any content at all - just the format.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@clemente  @UmanShahzad  @smarnach  You three are the ones who have worked the most on this course it seems; would you prefer the approach I'm proposing in this PR (hand-edit + diff friendly), or the approach of using Studio for future edits?

**Comment by smarnach** [comment]
@bradenmacdonald For most edits I prefer to edit by hand, but when creating a substantial amount of completely new content I'd prefer to use Studio.  This doesn't conflict with the approach you propose, though – we can simply use Studio to create the content, and then export and manually merge the files.

**Comment by bradenmacdonald** [comment]
That's true. It would just create an extra step when using Studio for major edits, but I think the trade-off is worth it.

**Comment by antoviaque** [comment]
@bradenmacdonald I would prefer to continue dogfooding - ie using Studio, like our clients. It's useful to be in the shoes of people creating courses using the tools that we help build sometimes, and that's one of the rare occasions we do this.

**Comment by bradenmacdonald** [comment]
@antoviaque  It's still dogfooding, because we're still using Open edX. Some of our clients hand-edit OLX (HarvardX, MIT), and it's a fully-supported workflow for the platform. This course is mostly HTML and has no fancy XBlocks, so there's not really anything special about using Studio for this. And in fact I think most of us who work on this course are already not using Studio for these small edits, so this doesn't change that.

**Comment by clemente** [comment]
Studio always generates some useless code, like `<a href="…" target="[object]">` and `<span></span>` etc. so we always have to edit it by hand afterwards. And we also edit it to indent the HTML by hand (I think we're too perfectionist with that, but at least it enables clean diffs). When editing, I do it by hand and I use Studio just to get a reference, e.g. „what's the official way to create a link to another section?“, „what's the code to insert a video?“ etc. This can still be done with your approach.
I like your approach because moving small files around requires a lot of care. When you create a new unit, it has a name hash-like name, and just to rename it you have to move many files and change many IDs inside files, including inside files you're moving. The new approach is safer.

**Comment by bradenmacdonald** [comment]
@antoviaque  No, it's like Sven said: for this course, you can still use Studio as much or as little as you want, and this format is still editable in Studio; it's just that if you use Studio, you would have an extra step at the end before you commit the changes to this repo, to edit the OLX and make sure you're not overwriting the hand-edited files with auto-generated ones that aren't as nice.

And this whole change is reversible at any time by simply running Export from Studio and committing the resulting file here; I would just be annoyed if someone did that :p

**Comment by bradenmacdonald** [comment]
@antoviaque If they're technical enough to [checkout a git repo, change branch, export a tarball from Studio, create a new branch, extract the tarball to overwrite the contents of the repo, commit+push, and open a PR] then they're probably technical enough to handle adjusting the OLX too if needed :-p

**Comment by bradenmacdonald** [comment]
@clemente @UmanShahzad @smarnach @antoviaque  Could I get a formal review approval from at least one of you please :)

Then I'll merge now, and we can apply the same cleanup to the other sections of the course as we make revisions to them in the future.

**Comment by bradenmacdonald** [comment]
Thanks @UmanShahzad ! and everyone else :)

**Comment by antoviaque** [comment]
@bradenmacdonald 

> If they're technical enough to [checkout a git repo, change branch, export a tarball from Studio, create a new branch, extract the tarball to overwrite the contents of the repo, commit+push, and open a PR] then they're probably technical enough to handle adjusting the OLX too if needed :-p

That's easily reversible - ie we could stop using the PR process if needed - so that's fine. That's why I was asking about how easy it would be to revert what you did in this PR, so we keep the option if needed.

**Pull request merged**
