### PR TITLE
Suggest how to choose a substitute when on holiday

### PR DESCRIPTION
**Pull request by clemente**
Add some guidance about how someone can choose a substitute in a more direct way, without having to arrange new teams in your head or having to ask many people 1 by 1. The goal is to make it as straightforward as possible.

Some points to discuss:
- [ ] explain in which JIRA epic ticket to ping people. Management?
- [ ] mention what to do when subteam assignments change after choosing a replacement
- [X] consider whether using chat (very synchronous, back-and-forth) is ok
- [X] maybe mention whether it's preferable to find a substitute who's already on the team you're conceding, vs. someone new (including a newcomer)
- [X] maybe mention something to make it faster, like „whoever accepts first becomes the replacement“, rather than having to wait for answers from everyone and then choose again 

CC @bradenmacdonald @antoviaque

### CODE REVIEW

**Comment by antoviaque** [comment]
@clemente Thanks for creating this!

> explain in which JIRA epic ticket to ping people. Management?

That should go on the epics for which you need to find coverage - it will already have the reight people assigned/following them.

> mention what to do when subteam assignments change after choosing a replacement

That's a good question, and I don't have a good answer about this, I was also wondering about it. @bradenmacdonald What do you think? This is especially tricky since subteam assignments are usually changing until the very beginning of the month, so we can't really properly plan for this. Maybe subteam assignments need to be planned longer in advance? Maybe instead of monthly, they should be set, and then only change when needed - and then we could add hooks in the process when we change a subteam allocation to check the holidays it impacts? Likely something to factor in the discussions about subteams - they are often very heavy to handle, process-wise, and we might want to look for ways to make the processes surrounding them lighter.

> consider whether using chat (very synchronous, back-and-forth) is ok

As usual, it should be avoided, unless you get caught up by time and need to find a solution _pronto_. That usually means that was planned for too late.

> maybe mention whether it's preferable to find a substitute who's already on the team you're conceding, vs. someone new (including a newcomer)

If there is the choice, that can sometimes be better, but that can be left up to people offering to be a backup. It can also a good opportunity to onboard someone new.

> maybe mention something to make it faster, like „whoever accepts first becomes the replacement“, rather than having to wait for answers from everyone and then choose again

+1

**Comment by clemente** [comment]
@antoviaque I applied your changes.

> >  explain in which JIRA epic ticket to ping people. Management?
>
> That should go on the epics for which you need to find coverage - it will already have the reight people assigned/following them.

But e.g. „Hosting“ is a subteam, not an epic, so which hosting epic we choose?

**Comment by bradenmacdonald** [comment]
@antoviaque Yep, I definitely want to find a way to make the subteams process lighter, or eliminate subteams altogether if we can find some other mechanism for matching the right # of hours to each monthly+hourly client (which was the only reason for creating subteams).

> Maybe subteam assignments need to be planned longer in advance? Maybe instead of monthly, they should be set, and then only change when needed
Yup, sounds reasonable.

**Comment by bradenmacdonald** [comment]
@clemente @antoviaque For subteams, I was thinking that there wouldn't actually be any need to coordinate things in advance - it would just be assumed that the small projects team (as a team) will cover for any holidays on other subteams, and that would be worked out during each week's planning on Friday, by the subteam owner or the second person on the subteam if the lead is the one on holidays. That keeps it simple and should work 90%+ of the time. For example, if I'm the owner of the McKinsey subteam and I normally work 10h/week on that but I"m away, then on Friday the second person on the subteam (say Matjaz) would ping people on the small projects team on Friday and ask if one of them can take a 2pt McKinsey story that week.

It's only for epic ownership where coordination in advance is required and someone must specifically be asked if they can cover.

**Comment by antoviaque** [comment]
@bradenmacdonald It would be nice to be able to simplify this part - but how do we ensure that the proper amount of time will be assigned during someone's holidays? Normally each person is responsible for monitoring its own time on each subteam, but we would need a mechanism to ensure the subteam quotas are still matched during holidays - reassigning the hours explicitly to someone was helping with this (and even though we still had inconsistencies at times).

Also, this is helping ensuring that we *can* cover for that work at all, before accepting the holidays. If it's not possible to find enough hours from people in the small projects subteam, it means we should refuse the holidays. This was meant to be eventually replacing the "no more than X people off at once".

**Comment by bradenmacdonald** [comment]
@antoviaque 

> how do we ensure that the proper amount of time will be assigned during someone's holidays?

The small projects team should almost always have enough capacity for that - it includes enough margin for holiday coverage and small client tasks, and unless 3+ people were off for a whole week at the same time, it's unlikely there wouldn't be enough time. In addition, the small client tasks are often not urgent, so even if the existing holiday capacity is not enough, we can probably achieve it by delaying the small, non-urgent client tasks (but that should be rare). And I already answered the other part of this question: actually assigning work from someone on small projects to the other subteam "would be worked out during each week's planning on Friday, by the subteam owner or the second person on the subteam if the lead is the one on holidays"

> reassigning the hours explicitly to someone

I should point out that we don't actually have a mechanism to do this right now: there is no place to record who is replacing whom for each subteam when people are on holidays. There's nowhere on JIRA to put that (except if you or I edit the swimlanes, I guess), and there's no task to re-assign or calendar item to update. I don't think it's necessary anyways, as I said above. But if we decide it is necessary, we'll need to establish somewhere to record it publicly.

Anyhow, can we revisit this discussion after we complete the task to review and revise how we handle subteams? For example, if we get Crafty to review the monthly hour quotas for each client and post an update every week, taking into account previous months, etc. then we could eliminate the need for subteams altogether, and just stick with epic ownership, which would be much nicer.

**Comment by clemente** [comment]
> then we could eliminate the need for subteams altogether, and just stick with epic ownership, which would be much nicer.

What happens with those who don't own epics (e.g. newcomers) but have hours in e.g Hosting subteam?

I'd like Crafty to send regular reminders about the hours and quotas, to help planning.
I'd also like prefer avoiding the „subteam“ concept, because I can't see it anywhere, or record it, or check data about it. Better to use something which is already in Jira, like epics.

**Comment by clemente** [comment]
By the way the discussion about subteams can be moved to https://tasks.opencraft.com/browse/OC-3566

**Comment by bradenmacdonald** [comment]
Actually subteam discussion should be on the Google Doc that I'll link to from https://tasks.opencraft.com/browse/MNG-82

> What happens with those who don't own epics (e.g. newcomers) but have hours in e.g Hosting subteam?

No special action is required from you. At/before the next planning meeting, the subteam owner and/or epic owner should notice that you're away and ask someone from small projects to cover for your time. (I guess we could also ask you to do that instead of the subteam/epic owner, but that becomes difficult if you're away for multiple sprints or you leave several days before planning happens. So I think the epic/subteam owners should handle that.)

**Comment by bradenmacdonald** [comment]
@antoviaque @clemente BTW, this repo is public so it's probably not the best place for extended discussions like this?

**Comment by antoviaque** [comment]
@clemente To conclude, for the scope of this PR (ie with the current process):

>  At/before the next planning meeting, the subteam owner and/or epic owner should notice that you're away and ask someone from small projects to cover for your time. (I guess we could also ask you to do that instead of the subteam/epic owner, but that becomes difficult if you're away for multiple sprints or you leave several days before planning happens. So I think the epic/subteam owners should handle that.)

Are subteam owners responsible for tracking people's time commitments currently? I'm not sure subteam owners would like to do this. It's more an individual responsibility imho - if I'm in subteam X, I have to do Y hours/week, or to ensure someone else does it for me if I go away.

> But e.g. „Hosting“ is a subteam, not an epic, so which hosting epic do we choose?

I would say pick one, preferably one on which there are already members of the small epics subteam if any. If not, pick any of the epics - it's mainly to ensure other people from that subteam are aware of that discussion, and we don't have a place to discuss at the subteam level currently.

> mention what to do when subteam assignments change after choosing a replacement

For now we can make it the responsibility of the person who has accepted to cover to bring it up, if he/she is moved out of the small epics subteams and can't provide coverage that has been previously agreed on.

> BTW, this repo is public so it's probably not the best place for extended discussions like this?

I'm fine with having these types of discussions in public - I actually think we could default more to truly public when our discussions aren't related to client work. Did I mention that I liked transparency and openness? :p

**Comment by antoviaque** [comment]
@bradenmacdonald I haven't answered this btw:

> I should point out that we don't actually have a mechanism to do this right now: there is no place to record who is replacing whom for each subteam when people are on holidays. 

There is - I ask people who take holidays to write it in their calendar entry.

**Pull request merged**
